services:
  - type: web
    name: MisFinanzasOriginal
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        sync: false
      - key: Authentication__Google__ClientId
        sync: false
      - key: Authentication__Google__ClientSecret
        sync: false
      - key: Authentication__Microsoft__ClientId
        sync: false
      - key: Authentication__Microsoft__ClientSecret
        sync: false
      - key: EmailSettings__FromEmail
        sync: false
      - key: EmailSettings__FromName
        value: Mis Finanzas